export const actionsTyps = {
  GET_STOCK_LIST: 'GET_STOCK_LIST',
  ERROR_GET_STOCK_LIST: 'ERROR_GET_STOCK_LIST',
  FETCHING_STOCK_LIST: 'FETCHING_STOCK_LIST',
  GET_STOCK_HISTORY: 'GET_STOCK_HISTORY',
  ERROR_STOCK_HISTORY: 'ERROR_STOCK_HISTORY',
  FETCHING_STOCK_HISTORY: 'FETCHING_STOCK_HISTORY',
  SET_SELECTED_STOCK: 'SET_SELECTED_STOCK',
};