export const actionsTyps = {
  GET_STOCK_LIST: 'GET_STOCK_LIST',
  ERROR_GET_STOCK_LIST: 'ERROR_GET_STOCK_LIST',
  FETCHING_STOCK_LIST: 'FETCHING_STOCK_LIST',
  GET_HISTORY_DATA: "GET_HISTORY_DATA"
};